### ISSUE TITLE
in web ui homepage, "node time" is, in fact, client time

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#100]
It seems that, instead of using POST to query the time in the node, we use JS to know what time it is on the client device.
This seems obviously wrong in so far as:

1. if client time is wrong, the user thinks node time is wrong.
2. if node could not sync using ntp, the user would not notice.
3. when node is crashed, the user has the illusion that it is still running, because the displayed time is `now`.

**Comment by PolygonalTree** [comment]
You were right. Solved with b11101f
