### ISSUE TITLE
Exception raised before the call to "run" kills the server

### ISSUE THREAD

**Issue by PolygonalTree** [gilestrolab/pySolo-Video#101]
This happens when device_server.py is run in debug mode and picamera is not available, this causes an exception in cameras.py (logged as warning) but logging file is not defined yet (at that point) and "I/O error Attempt to write to a closed file" error is raised and server stops.
Possible solution: define logging file before cameras.py is loaded.

**Comment by qgeissmann** [comment]
This issue was moved to gilestrolab/ethoscope#7
