### ISSUE TITLE
devices should be rescanned automatically at frequent time intervals

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#105]
So far, the `device_map` is only updated by implicit user request.
If device IPs change, backup will crash and...

**Comment by ggilestro** [comment]
I'd strongly recommend using avahi for this. Scan only once then refer to
machines with syntax hostname.local

--
Giorgio F. Gilestro
http://gilest.ro

On Thu, May 14, 2015 at 8:25 AM, Quentin Geissmann <notifications@github.com

**Comment by qgeissmann** [comment]
I agree, but it means we also need to set different host name for machines e.g. `hostname = machine_id`

**Comment by qgeissmann** [comment]
As backup is v unstable, I am implementing a standalone backup daemon which will perform incremental backups independantly of the bottle script.

**Comment by qgeissmann** [comment]
@PolygonalTree device map now has a "backup_path" field. this is the full path the the `.db` file where the data from this device is being saved. I think it would be helpful to tell the user when was the last backup, based on, for instance, the last time stamp of this file.

**Comment by qgeissmann** [comment]
testing is going ok: independent backup daemon seems to be a good paradigm. 
Closing issue
