### ISSUE TITLE
"start" POST should include a dict with additionnal information

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#106]
We are starting to have different arenas, so, I would like to be able to not only "start a device", but "start a specific arena". Long term, we could use bare codes, but I still think this is a needed feature.

**Comment by PolygonalTree** [comment]
This has been addressed and a first implementation is available on dev but we have to discuss what additional information is required.

**Comment by qgeissmann** [comment]
This issue was moved to gilestrolab/ethoscope#8
