### ISSUE TITLE
Display where file will be saved in the web interface.

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#107]
@PolygonalTree  Some feed back on the implementation of this feature:

1. The file name includes a development prefix `/data1/todel/psv_results`
2. Since the name is really long, we could truncate it (e.g. /psv_results/.../2012-12-31_11:32:12_xxxxxxx.db). In addition, if it is not too hard, we could have a tooltip on hover to show full name.
3. We should have a download link to the file on the name.
4. Finally, and most importantly, the path to the file can be erroneous in the following scenario: a device is stopped (internally, the path to the data points to the path of the data from the last experiment). The user starts the device. Since `device_map` is not amended (no re-scanning), the location of the file still matches the old `.db`. It is obviously saved at the right place, but displayed at the wrong location. It would be interesting to force refreshing device info at start, and update the path in the user interface.

**Comment by PolygonalTree** [comment]
1cf0959

**Comment by qgeissmann** [comment]
[1.] fixed by cc6595c

**Comment by PolygonalTree** [comment]
Point 4. Rescan the network from device page at start seems to have no effect. It is always picking up the previous db, not the current one. Maybe we are requesting the path before it is created.
