### ISSUE TITLE
`Monitor` should expose last frame

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#11]
Frames should be buffered instead of in temporary variables.
Also need an attribute to access frame.
@PolygonalTree I will make a *deep copy* of the buffer upon request for safety. I am assuming you are not going access the attribute at a high frequency, are you?

**Comment by PolygonalTree** [comment]
No, it should be very low frequency, one frame every 30 or 10 seconds 
but only if the user is visualizing the website. We have to be in mind 
that this does not affect to the speed of tracking.


On 16/01/15 11:15, Quentin Geissmann wrote:
>
> Frames should be buffered instead of in temporary variables.
> Also need an attribute to access frame.
> @PolygonalTree <https://github.com/PolygonalTree> I will make a /deep 
> copy/ of the buffer upon request for safety. I am assuming you are not 
> going access the attribute at a high frequency, are you?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gilestrolab/pySolo-Video/issues/11>.
>

-- 
Luis Garcia
Polygonal Tree
Custom hardware and software solutions for laboratories
www.polygonaltree.co.uk <http://www.polygonaltree.co.uk>

**Comment by qgeissmann** [comment]
Fixed by 39627ea..f3f39bd. You should be able to do `monitor.last_frame`. Closing
