### ISSUE TITLE
Dowload incomplete gzip data on client

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#12]
@PolygonalTree  As a warning, it is **not safe** at all to download partial `gzip` to the client.
I think we must discuss a way do that better.
Also, we must think about whether we offer to the client user the ability to deflate the gzip using JS.

**Comment by ggilestro** [comment]
Agree. AUR is really the easiest IMO. one can still upload a pkg.tar.gz and
install it with pacman as alternative to a zip.
If you really have to go with zip, at least md5sum it.


--
Giorgio F. Gilestro
http://gilest.ro

On Thu, Jan 29, 2015 at 7:33 PM, Quentin Geissmann <notifications@github.com

**Comment by qgeissmann** [comment]
@ggilestro Sorry, I am talking about downloading **result files** from client to node.
If we really want to ba able to download data before completion of the analysis, this should be taken in consideration.
I will make an AUR for `psv-package` regardless ;).

**Comment by PolygonalTree** [comment]
Regarding this issue. If the experiment is running and the gzip is been written when the user downloads it, then the gzip file is corrupted, or it can show some errors or data lost. 
I am not sure what it is the best approach. We can try to unzip the file locally with JS, but that means that we can create some RAM problems in the client computer if the file is to big. 
If we use the Node, an option is to download to a known folder this data and as we discussed in the past have some high capacity storage attached to the Node.  Then, this downloaded file can be decompressed and served to the client, or send it compressed or decompressed to some external storage like amazon or others.
what do you think @qgeissmann ?

**Comment by qgeissmann** [comment]
Assuming we get uncorrupted data on the node, since we are running `python` in the node, we should be able to:

* Stream uncompressed data to client
* Rsync to backup server
* Deflate data on demand  before sending them to client, and removing them after download completion

**Comment by qgeissmann** [comment]
Fixed on the server-side by implementation of a custom file writer with a default chunk size of 30min. See 40c01ce334dac1f667b6ff2aebe43d8f59b244e9 (https://github.com/gilestrolab/pySolo-Video/blob/psv-package/src/pysolovideo/utils/io.py).

Still need to implement fetching on the node-side

**Comment by qgeissmann** [comment]
Using an SQLite file to save data (as opposed to csv or cvs.gz) on the fly provides many advantage. Briefly,

* We control the type of the binary data being saved (eg `SMALLINT`) => save lots of space
* We can make SQL queries => have a optimized way to subset data without storing it in RAM. This can be used by the node as well for visualization. Possibly large CSV will not fit in memory, for post hock analysis. SQL allow, at least, to have one table per ROI, so we can analyses one ROI at a time.
* We can import SQL tables as `R` dataframes seamlessly.
* We can compress SQLite DBs after acquisition for long term storage (7z gave me about 4x in reasonable time).
* Concurrent rsync of device DBs with Node mirror seems to work perfectly as well (no data corruption).

Therefore, I have implemented SQLite support, which should be default (see c92eaf07def10965f74728cf1c1c73951d677165).
