### ISSUE TITLE
Set the device name from node

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#17]
In practice it would be simple to have a human friendly name for each device.
Ideally, the user can set the name from the interface and, for instance, write the name on each machine.
Internally we will obviously keep using `machine_id` as it is guarantied unique.
What do you think @PolygonalTree?
Maybe we should have add a configuration file which can store this sort of info.

**Comment by PolygonalTree** [comment]
We have already a variable named "name" that is returned by the device_server. This name is storage in some txt file in the device and can be changed by the user from the website interface, yet to implement in this version, but I am working on it.

**Comment by qgeissmann** [comment]
Do you know where you want to save the text file? `/etc/psv/config.txt`?
We must consider permissions as well. I figure you intend to deamonise the script, hence run is as `root`, right?

**Comment by PolygonalTree** [comment]
We can run as root or as another user, root is only necessary if we run the server in ports with a number less than 1024.

**Comment by qgeissmann** [comment]
Since you start the script at boot time, I would think it is easier if root run it, right?

**Comment by qgeissmann** [comment]
I assumed this is a `wontfix`. as you will set device name manually when generating SD cards. closing
