### ISSUE TITLE
SleepDep adapters should be white on their basis

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#23]
The adapters between servos and tube caps needs to be white for few (~3mm) on the side of the servos.

**Comment by ggilestro** [comment]
@qgeissmann can you take a IR picture of white and black ABS and see if they look any different? It would be better to use materials that have different colors under IR light for in the future we may have visible filters on the camera again.

**Comment by qgeissmann** [comment]
I can do that tomorrow. The black arena is locked up (experiment running)  in the incubator atm.

**Comment by PolygonalTree** [comment]
Remember that the material that you have in black or white is PLA, I suggest to see if Nylon (arenas) or other plastics that you can get in the lab (ABS) seems to be different.

**Comment by qgeissmann** [comment]
Just need testing on that, but it is essentialy solved
