### ISSUE TITLE
Use USB sticks for data partition

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#25]
Should mount memory sticks on the devices in order to save data.
e.g.
* `/dev/sda1 ===> /var`
* `/dev/sda2 ===> /psv_data` (mind the permissions)

This should be added to the installation scripts (make `/data` dir, `fstab` and copying `/var`)

This way, the sd card will be implicitly read only (except when updating software).

It may be advantageous to use Btrfs on the data partition so we can compress results on the fly, transparently (see https://wiki.archlinux.org/index.php/Btrfs#Compression).

**Comment by qgeissmann** [comment]
@PolygonalTree this is sorted, isn't it ?

**Comment by PolygonalTree** [comment]
I think so, we have to discuss if Btrfs or ext4

**Comment by qgeissmann** [comment]
last estimation at ~2.5 FPS, ~30 flies => 2M/h (i.e. ~ 1GB for a 5day experiment -- per device). So, maybe we can use Btrfs on the node SSD.

**Comment by qgeissmann** [comment]
closing, this is solved.
