### ISSUE TITLE
Interface to browse past results in node

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#33]
So far, it is only possible to save results from open monitors. We need to have a way to collect old data backed-up non the node even if we are running new experiment.

This is also to relate to the directory structure we should be saving the files under, how we delete old files...

**Comment by qgeissmann** [comment]
I suggest we change the convention to save results as:

`/psv_results/device_id/device_name/date_time/*`

This way, in the web interface, we can then only show `device_name` as it is human friendly, and use device id in the background. On the plus side, we do **not need to store a persistent map** {device_id: device_name}, this strategy will **make data available even if devices are unplugged**.

@PolygonalTree Does this make sense?

**Comment by qgeissmann** [comment]
bf6e953 set the dir structure as the convention described above

**Comment by qgeissmann** [comment]
ok so :
I have implemented , in `server.py`

```python
@app.get('/result_files/<type>')
def result_file(type):
    """
    :param type:'all', 'db' or 'txt'
    :return: a dict with a single key: "files" which maps a list of matching result files (absolute path)
    """
```
e.g. you should get a response like:

`{"files": [/psv_results/3a92bcf229a34c4db2be733f6802094d/SM15-001/2015-03-06_11-46-13/2015-03-06_11-46-13_3a92bcf229a34c4db2be733f6802094d.db]}`

@PolygonalTree is that ok ?

**Comment by qgeissmann** [comment]
btw, merged on `psv-dev`

**Comment by PolygonalTree** [comment]
Added new interface with a searchable table, you can search by name, date or type of file.
