### ISSUE TITLE
db incremental primary key

### ISSUE THREAD

**Issue by PolygonalTree** [gilestrolab/pySolo-Video#35]
This error is probably caused by not using a incremental id as primary key:
Sorry there has been an error: Traceback (most recent call last): File "/home/psv/pySolo-Video/src/pysolovideo/web_utils/control_thread.py", line 153, in run self._monit.run(rw) File "/home/psv/pySolo-Video/src/pysolovideo/tracking/monitor.py", line 217, in run raise e OperationalError: (1054, "Unknown column '1424454841573L' in 'field list'")

**Comment by qgeissmann** [comment]
solved in 8d6267d
