### ISSUE TITLE
device are not always detected in scan

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#40]
Let us just increase time out.
Alternatively, we could ping simply ping http://stackoverflow.com/questions/2953462/pinging-servers-in-python, this should be faster then url request.

**Comment by PolygonalTree** [comment]
We can ping to see if there is something alive in that address and then ask for the data.

**Comment by qgeissmann** [comment]
The best would be to (pseudocode):
```python
p =  ping()
if p:
    req = request_url(long_timeout)
    if not req:
        REPORT ERROR
    else:
         use this device
else:
    pass
 ```
This way we can identify if the server has had a problem (ping ok, but no response from bottle). And, for instance, advice a reboot/wait.

**Comment by qgeissmann** [comment]
Ok, I will do that now,
