### ISSUE TITLE
Raspberry PI takes longuer and longuer 

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#41]
Over 18h, we observe a general increase in delay between frames.
This is possibly due to database inflation issue.
![todel](https://cloud.githubusercontent.com/assets/1399684/6372009/c52e8018-bcf8-11e4-96d7-c04270512989.png)

**Comment by PolygonalTree** [comment]
What units is the time measured on. a.u = astronomical units (I think this is so much time between frames).

**Comment by PolygonalTree** [comment]
Take a look to this (index issues) Did you change the index to be incremental and a long int?
http://dba.stackexchange.com/questions/28719/query-performance-degrades-with-time-and-use

**Comment by qgeissmann** [comment]
Arbitrary unit...you physicist :p.
I did change it to `id INT  NOT NULL AUTO_INCREMENT PRIMARY KEY`.
Will look into that right now,

**Comment by qgeissmann** [comment]
OK so this is definitely caused by mysql insert queries.
two things were done to solve this issue:

1. multiple row inserts
2. use multiprocessing and a `Queue` of mysql commands

Altogether, this seems to have solved the problem!!
I still need to work a bit on making this cleaner since asynchronous writing implies waiting for processes to close...

**Comment by qgeissmann** [comment]
done by c2c8c84b70875ad87c5272f19d90b67237683941!
