### ISSUE TITLE
Ntpd server config in devices

### ISSUE THREAD

**Issue by PolygonalTree** [gilestrolab/pySolo-Video#45]
configuration file needs to be changed to use the node as server.

**Comment by qgeissmann** [comment]
@PolygonalTree po is that done ? close if yes ;)

**Comment by PolygonalTree** [comment]
He have to check if the hour in the test that we made yesterday is OK.
If that is OK and you do not touch any ntp code then this is fixed.

**Comment by qgeissmann** [comment]
device it at GMT
