### ISSUE TITLE
display pkg version in device list (along with device ip/name/...)

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#52]
So we can check update status.
@PolygonalTree please, also display version of the node repo in the update tool.
This is good for us and good for users should they they need to report it.

**Comment by qgeissmann** [comment]
@PolygonalTree in the update system I would prefere if we had a table showing all devices connected with the following headers:

`device name, status, software version, ip, id`

Otherwise, it is hard to know whether the devices are not detected, or already up to date...
Does this make any sense?

**Comment by PolygonalTree** [comment]
50daa67 should solve this. Please check on the development version.

**Comment by qgeissmann** [comment]
@PolygonalTree, can you add the software version easyly to the **control panel** device list though?
and also display the version for the node in `/more` ?

**Comment by PolygonalTree** [comment]
This is done.
