### ISSUE TITLE
update DEVICE works, but do not seem to restart device afterwards

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#53]
This would be easier to debug if #52 was fixed

**Comment by PolygonalTree** [comment]
Yes, I will fix #52.
Are you using debug = restart.sh or production = restar_production.sh

**Comment by qgeissmann** [comment]
I am using the default setting on the actuall developent platform setup... 
so `RESTART_FILE = "./restart_production.sh"`. I guess this is untested, right ?

**Comment by qgeissmann** [comment]
I  am not actually sure device.service is NOT restarting. What I can tell is : 

* git was up to date
* service was running
* update manager did detect that `SM-001` needed update.
* after manual restart of the service -- through ssh -- update manager did not detect device as needed to be updated any more.

**Comment by PolygonalTree** [comment]
Yes it is untested, and the problem I think is that service restart does not change the environment.  I will take a look.

**Comment by PolygonalTree** [comment]
c5ba5e0 should solve that, be aware of trying in your computer, it will switch off.

**Comment by PolygonalTree** [comment]
Please if you have time, can you check this on the development setup as follows?
1. Make a git push to psv-package
2. detect if update of node and attached devices are needed
3. update all
4. If devices are still as updated needed:
4.1 reload website and check again for updates. (sometimes the re-check takes a while)
4.2 if the device is still there, check version on device with "git rev-parse psv-package" through ssh and the version showed in the website is identical.
4.3 If they are not identical, try to restart service through ssh with "systemcl restart device.service"
4.4 reload website and check for updates, if still here then restart is not working as expected. 
4.5 Try to use "systemctl stop device" and then "systemctl start device"

**Comment by qgeissmann** [comment]
after check, I do not see the sam commit id on device after update.
@PolygonalTree  I manage to update the loca repo manually **only with** `git pull origin psv-package`. **Not** with `git pull`.
I suggest we update `device_server.py` git command:

```python
@api.post('/update/<id>')
def update_system(id):
    if id == machine_id and control.info['status'] == 'stopped':
        try:
            device_update = subprocess.Popen(['git', 'pull'],
                                             cwd=GIT_WORKING_DIR,
                                             stdout=subprocess.PIPE,
                                             stderr=subprocess.PIPE)
            stdout, stderr = device_update.communicate()
```
I will do that, ok ?

**Comment by PolygonalTree** [comment]
I think that is because the command we use to clone is not right we forgot to add the branch. Got clone  --branch psv-package --single-branch node@192.169.123.1/path_to_pysolo.git
This should create a clone repo with the branch configured and that way only git pull woul be required, I think.

**Comment by qgeissmann** [comment]
Our solution is to simply `exit(status)` python scripts after update or failure . Then systemd is configured to autorestart our services, if needed, every five second.
