### ISSUE TITLE
power off devices does not work

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#55]
When clicking on power off device, after having stopped a device:

1. a modal window appears
2. when clicking on poweroff, nothing happends and the window remains top level
3. we are forced to cancel
4. we can still use the device/connect to ssh

it would help to be able to poweroff the device if restart service is not working (see #53 )

**Comment by PolygonalTree** [comment]
c5ba5e0 should solve that, be aware of trying in your computer, it will switch off.
