### ISSUE TITLE
daemon starting order

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#62]
in principle, `ntpd` should start before `device` and `node` services.
In addition, `mysqld` service is requiered on device.

**Comment by PolygonalTree** [comment]
I updated the node.service and script.service to start after ntpd.service. Please test it on development setup, and close if it is solved.

**Comment by qgeissmann** [comment]
I cannot see any `mysql` prerequisite  on device.service... how does that work?

**Comment by PolygonalTree** [comment]
Is mysql or mysqld required?
If it is required before start you should add it in Wants=

**Comment by qgeissmann** [comment]
`mysqld` is required by device. I will add it
