### ISSUE TITLE
Why is node in device map?

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#64]
When scanning for updates, it seems that Node is added to device map...
Do we really need that?
This create bugs/features? like : 

![screenshot from 2015-03-09 14 10 17](https://cloud.githubusercontent.com/assets/1399684/6556570/51a39b70-c666-11e4-8919-9a5cd4e0046a.png)

**Comment by PolygonalTree** [comment]
Because it is added to the devices list when you scan for an update and not re-scan.

**Comment by qgeissmann** [comment]
I understand, but is that needed? it seem confusing... what is our solution?

1. not add it to device map as device map is conceptually the list of **devices**
2. fix js to ignore node devices...

**Comment by PolygonalTree** [comment]
I will implement 1.

**Comment by PolygonalTree** [comment]
649d29ea should solve that.
