### ISSUE TITLE
Device not shown in update:

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#65]
My device map looks like:
```
{'node': 
    {'status': 'ON', 'version': '22c16ce15e708ae47d949226fd87692a009d3ab8', 'name': 'Node', 'id': 'Node'}, 

u'3a92bcf229a34c4db2be733f6802094d': 
    {u'status': u'stopped', u'error': None, u'name': u'SM15-001', 'ip': 'http://129.31.135.141', u'dbg_img': u'/psv_data/results/dbg_img.png', u'last_drawn_img': u'/tmp/psv_LV2gPf/last_img.jpg', u'db_name': u'psv_db', u'version': u'', u'time': 1425904835.655987, u'monitor_info': {u'last_positions': None, u'fps': 0, u'last_time_stamp': 0}, u'log_file': u'/psv_data/results/psv.log', u'type': u'sm', u'id': u'3a92bcf229a34c4db2be733f6802094d'}
}
```
Note the `version=""` for the device.
In `control_thread.py`:
Why do we have both:

`{"psv_version": pkg_resources.get_distribution("pysolovideo").version}`  (in run) **and** `{"version": version}` (in the constructor). @PolygonalTree  I will remove the former, if it is ok... Then I will pass/inject the correct version checksum from `device_server.py`

**Comment by PolygonalTree** [comment]
we have both because I thought you where using psv_version for something.
If the version is not shown in the device maybe it is because the get_version helper is not working due to a bad configuration in variable BRANCH

**Comment by qgeissmann** [comment]
ok fixed. Version is both in `_info.metadata` and `_info`. however, it is the same version. and is defined in __main__.
Also, my git working dir setting was wrong.
