### ISSUE TITLE
Node try to wait for device to stop when ctrl+c is send to it. This show an error

### ISSUE THREAD

**Issue by PolygonalTree** [gilestrolab/pySolo-Video#66]
That means that node can only be updated / restarted / poweroff when all the devices are stopped?

I get this traceback:

´´´
^CINFO:root:Keyboard interrupt: stopping backup
INFO:root:Joining acquisition processes
has_been_running_once True
INFO:root:Try final mirroring of the DB
INFO:root:Stopping acquisition thread
INFO:root:Joining process
INFO:root:Waiting for device to stop...
ERROR:root:Traceback (most recent call last):
  File "/data1/PolygonalTree/Github repo/pySolo-Video/psvnode_server/psvnode/utils/acquisition.py", line 169, in run
    raise Exception("Last backup timed out. Device did not stop, or could not reach device.")
Exception: Last backup timed out. Device did not stop, or could not reach device.
INFO:root:Joined OK
INFO:root:Closing server
´´´

**Comment by qgeissmann** [comment]
In practice, `os._exit()` is used by node to shut itself down, so we will not wait for devices/acquisition to stop. For development purposes, you can CTRL+C twice, so you raise an exception whilst waiting for devices to stop, which stops the device.
