### ISSUE TITLE
Update tool fails to update origin (from github), without displaying error

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#69]
Therefore, even if new version is available on origin, the user sees that everything is up to date...
This is confusing. Internally, we should have 3 variables (in the node):

* version on remote
* version on bare repo (origin)
* version of the running pkg

I think can be be pretty stringent when updating system.
Thant is we should request internet connection to be active, otherwise we don't allow any update.

**Comment by qgeissmann** [comment]
I guess one problem could be that we don't handle errors from `git fetch -v origin $BRANCH:$BRANCH`

**Comment by qgeissmann** [comment]
other clue:
in 
```python
@app.get('/update/check')
def check_update():
    ...
    origin_version = get_version(GIT_BARE_REPO_DIR, BRANCH)
    ...
```
however, origin_version is **not global**

**Comment by PolygonalTree** [comment]
I added the error to be rendered in the website. Error in check updates are loaded in update['error'] object.
