### ISSUE TITLE
Downloading zip files

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#74]
* Where do we store temporary zip files
* how do we ensure they will removed after dl
* how long does it take to zip files (unsure we use low compression rate)?

**Comment by PolygonalTree** [comment]
There is another problem with this. 
With the new table searching system, the checkboxes for selecting several files are not working due to a problem between angular and datatables. Working on it.

**Comment by qgeissmann** [comment]
At the moment, all the dir structure is added to the zip. I would expect to simply chunk all files in zip.
Then, we should have a `tmp_results` dir in  `psv_result`, and blacklist it from the walk.
Whenever the server is restarted, we should erase the content of the `tmp` dir.
Also, @PolygonalTree  can we bind a "successful download" callback to erase individual zips?

Another possibility, is to have one unique zip per user session...

**Comment by PolygonalTree** [comment]
What happend if the Node is not reset in a while. Would the /tmp/ be very big?
I will think about the callback, I have to check how to know when the download is complete.
