### ISSUE TITLE
Debug image not updated

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#80]
When a debug image is shown, in the web browser, it is cached,  so when/if a new one is to be displayed, the cached one is displayed instead.
Obviously reloading web page is a quick fix for the user.

**Comment by PolygonalTree** [comment]
Please test. If solved, close. I am using a variable that I am not sure if it will reload the image.

**Comment by qgeissmann** [comment]
Not solved. No image is shown instead "No debug image".

**Comment by PolygonalTree** [comment]
hope that this changes solve the problem. a4fee26

**Comment by qgeissmann** [comment]
This is still an issue

**Comment by PolygonalTree** [comment]
commit f7633a a fix? need testing.

**Comment by qgeissmann** [comment]
seems to work, nice job,
closing
