### ISSUE TITLE
Web interface should warn user when trying to update running devices

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#83]

**Comment by PolygonalTree** [comment]
According to the software it shouldn't be possible to update running devices or select them to update.

**Comment by qgeissmann** [comment]
It is not possible, but the interface does not show any sort of warning ("Devices [XX,YY,ZZ] cannot be updated since they are running."). This is just an #improvement really.

**Comment by PolygonalTree** [comment]
OK, will take a look into that.
