### ISSUE TITLE
Device list should be a table

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#87]
As discussed with @PolygonalTree the device list should be a table with fields:
`Name,status,time(since in this status),ip,id,...`

At this stage, it would be also good to think of a way to have tick boxes to select several devices in the table. This way, we could, for instance, "start all devices".

The main reason for doing this is that it would allow us to work with many (100+) devices.

**Comment by PolygonalTree** [comment]
I have made a commit to show a list, multiple selection is not yet implemented.

**Comment by qgeissmann** [comment]
Great. Just wrote a different issue (#93) for multiple selection/action. closing
