### ISSUE TITLE
Monitor IR light intensity is not enough

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#88]
At least on two different device (so probably on all), the amount if IR light is insufficient.
See :
![last_img](https://cloud.githubusercontent.com/assets/1399684/7086746/5e045416-df7c-11e4-8be4-8b0b267c4edf.jpg)

This is **very critical** as **tracking will not work during the night**

**Comment by qgeissmann** [comment]
After investigation, this appears to be a bug in V4L2 (or it's opencv binders). It seems that for some instances of `VideoCapture` (apparently rather randomly), the brightness does not adjust.
In addition, images look much sharper with native `raspevid`.
As a result, I will implement a `PiCamera` class using `raspvid`.

**Comment by qgeissmann** [comment]
This seems to be a good start : 
http://www.pyimagesearch.com/2015/03/30/accessing-the-raspberry-pi-camera-with-opencv-and-python/

**Comment by PolygonalTree** [comment]
Quentin,
Is this solved then?


On 13/04/15 12:17, Quentin Geissmann wrote:
>
> After investigation, this appears to be a bug in V4L2 (or it's opencv 
> binders). It seems that for some instances of |VideoCapture| 
> (apparently rather randomly), the brightness does not adjust.
> In addition, images look much sharper with native |raspevid|.
> As a result, I will implement a |PiCamera| class using |raspvid|.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gilestrolab/pySolo-Video/issues/88#issuecomment-92317582>.
>

-- 
Luis Garcia
Polygonal Tree
Custom hardware and software solutions for laboratories
www.polygonaltree.co.uk <http://www.polygonaltree.co.uk>

**Comment by qgeissmann** [comment]
sure, but need to install `picamera` on target devices. see postintall script.
Also need to assess performance.

**Comment by qgeissmann** [comment]
we run now at 1fps (instead of 2), but it is fixed. will try to improve performance tomorrow.
