### ISSUE TITLE
Elapsed time in status wrong

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#92]
The reported time seems wrong when the device is stopped (e.g. I get large, constant, values just after stopping the device).
In addition, the time is not human friendly (e.g. 'elapsed time is status = 55932.008').

I would suggest we change for a format such as "**In status since** Tue, 14 Apr 2015 09:36:13 GMT"

**Comment by PolygonalTree** [comment]
When you stop the device there is no time in the status that we can use. When it is running we use the "last_time_stamp". But when it is stopped we lost any information. 
Maybe we have to implement something to show the time that has been stopped or just show nothing instead.

**Comment by qgeissmann** [comment]
I think we discussed about the fact that the "time" field in `device_info` is, in fact, the unix time stamp of the time the device entered its current status. this means it should be straightforward to format it in human readable time.

**Comment by PolygonalTree** [comment]
I updated the code to use time from device_info, not sure if that is going to be all right.

**Comment by qgeissmann** [comment]
looks nicer! cheers!
