### ISSUE TITLE
Update system reports error when everything is OK

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#95]
When a new version is available, we always get errors such as

```
Error details: POST git-upload-pack (959 bytes) From https://github.com/gilestrolab/pySolo-Video e9b8129..9a859c9 psv-dev -> psv-dev
```
Simply ignoring the error and proceed to update works perfectly though.

**Comment by PolygonalTree** [comment]
It is a bug on Git:
http://stackoverflow.com/questions/10790232/hanging-at-post-git-receive-pack-chunked

**Comment by qgeissmann** [comment]
This issue was moved to gilestrolab/ethoscope#5
