### ISSUE TITLE
Preview image does not need to be saved to a file

### ISSUE THREAD

**Issue by PolygonalTree** [gilestrolab/pySolo-Video#99]
According to this thread we can simply remove the jpg writing saving time. 
http://stackoverflow.com/questions/28029702/returning-image-using-stream-instead-of-static-file-in-bottle

**Comment by qgeissmann** [comment]
I like saving to file for debugging purposes (e.g. being able to see the last image if bottle crashes).
Also, `/tmp` is mounted on a tmpfs, so I expect negligible cost.
If it is all right, I am closing,
